# Uncomment the next line to define a global platform for your project
# platform :ios, '14.0'

target 'WPRK-iOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for WPRK-iOS
    pod 'WPRKSDK', :path => '../WPRKSDK'
  # Add the Firebase pod for Google Analytics
    #pod 'Firebase/Analytics'

  # For Analytics without IDFA collection capability, use this pod instead
    # pod ‘Firebase/AnalyticsWithoutAdIdSupport’

  # Add the pods for any other Firebase products you want to use in your app
  # For example, to use Firebase Authentication and Cloud Firestore
    # pod 'Firebase/Auth'

end
